### ISSUE TITLE
No module named 'mdexport'

### ISSUE THREAD

**Issue by johnblommers** [andy-verstraeten/mdexport#1]
Installed using `pip3 install mdexport` then attempt to use it:

```
mdexport --version
Traceback (most recent call last):
  File "/home/johnb/.local/bin/mdexport", line 5, in <module>
    from mdexport.mdexport import cli
ModuleNotFoundError: No module named 'mdexport'
```

**Comment by andy-verstraeten** [comment]
This was an issue i ran into when initially packaging the project. I've tested the latest version on mac and on linux. Could you give some insight into the OS/setup you have? 

Could you try:
pip3 install mdexport==0.0.8
(to make sure the latest version installs maybe there is any issue in publishing to pypi)

**Comment by johnblommers** [comment]
> This was an issue i ran into when initially packaging the project. I've tested the latest version on mac and on linux. Could you give some insight into the OS/setup you have?

I'm running PopOS Linux 22.04 based on Ubuntu.

> Could you try: pip3 install mdexport==0.0.8 (to make sure the latest version installs maybe there is any issue in publishing to pypi)

OK here goes:

```
pip3 install mdexport==0.0.8
Defaulting to user installation because normal site-packages is not writeable
ERROR: Ignored the following versions that require a different python version: 0.0.7 Requires-Python <4.0,>=3.11; 0.0.8 Requires-Python <4.0,>=3.11
ERROR: Could not find a version that satisfies the requirement mdexport==0.0.8 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6)
ERROR: No matching distribution found for mdexport==0.0.8
```

Hmmm this suggests my Python isn't new enough:

```
python --version
Python 3.10.12
```

**Comment by andy-verstraeten** [comment]
I've removed the non functional version from pypi and new version with a dropped python version requirement. So things should be solved by now.

On your os make sure weasyprint is installed.
```bash
pip3 install mdexport
apt install weasyprint
```
hopefully this resolves the issue.

**Comment by johnblommers** [comment]
> I've removed the non functional version from pypi and new version with a dropped python version requirement. So things should be solved by now.

The original error message is indeed gone but another has taken its place. I did a `pip3 uninstall mdexport` followed by a `pip3 install mdexport` and then:

```
mdexport --version
Traceback (most recent call last):
  File "/home/johnb/.local/bin/mdexport", line 5, in <module>
    from mdexport.mdexport import cli
  File "/home/johnb/.local/lib/python3.10/site-packages/mdexport/mdexport.py", line 4, in <module>
    from .cli import (
  File "/home/johnb/.local/lib/python3.10/site-packages/mdexport/cli.py", line 30
    return f"Provide one of the following templates: {",".join(template_options)}"
                                                       ^
SyntaxError: f-string: expecting '}'
```

The selfsame error occurs using the  `--help` option. A slight variation occurs using the full commandline:

```
mdexport publish file.md -o output.pdf -t invoice
Traceback (most recent call last):
  File "/home/johnb/.local/bin/mdexport", line 5, in <module>
    from mdexport.mdexport import cli
  File "/home/johnb/.local/lib/python3.10/site-packages/mdexport/mdexport.py", line 4, in <module>
    from .cli import (
  File "/home/johnb/.local/lib/python3.10/site-packages/mdexport/cli.py", line 30
    return f"Provide one of the following templates: {",".join(template_options)}"
```

**Comment by andy-verstraeten** [comment]
Sorry for the delay. It took some time to set up a similar environment as yours. 
In the version 0.1.1 it should be fixed. It seemed to be an issue with earlier python
versions.

**Comment by johnblommers** [comment]
> In the version 0.1.1 it should be fixed.

And it is! To get `mdexport` re-installed:

```
pip3 uninstall mdexport
pip3 install mdexport
```
